### ISSUE TITLE
Why the unnecessary bump to node 10? 

### ISSUE THREAD

**Issue by hulkish** [jerryjappinen/sass-values-loader#4]
[this](https://github.com/Eiskis/sass-values-loader/commit/16cd0bb261866928bbecfde148ab04770c765497) seems rather bizarre to be released in a patch, to me. There is also `lodash.isArray` being added in same commit - which has been natively available since node 4. 

I'd like to suggest to please change `engines.node` to `>= 6` (or even 8), please?

**Comment by jerryjappinen** [comment]
The patch was originally a fix for #2, but you're probably right in that the node version change was unnecessary.

I'll try to find the time to downgrade again soon.

**Comment by jerryjappinen** [comment]
@hulkish did you experience issues with the dependencies, or only the node version?

**Comment by hulkish** [comment]
we use node 8, so when a patch released it caused engines check to fail on yarn/npm install

**Comment by jerryjappinen** [comment]
@hulkish I pushed an update that removes the unnecessary version definition, hope it fixes the problem. Thanks for filing the ticket and sorry for causing the issue, pure carelessness on my part!
